import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import { BeatLoader } from "react-spinners";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { ThemeProvider } from "@/components/theme/theme-provider";
import SidebarWrapper from "@/components/layout/sidebar-wrapper";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.variable} ${geistSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="font-[family-name:var(--font-geist-sans)] flex relative min-h-screen overflow-x-hidden">
            <div className="relative flex w-full h-screen">
              <SidebarWrapper />
              <Suspense fallback={
                <div className="w-full h-full flex justify-center items-center z-50">
                  <BeatLoader color='#ffffff' size={10} />
                </div>
              }>
                <main className="flex flex-col flex-1 overflow-y-auto overflow-x-hidden scrollbar-thin relative">
                  {children}
                  <Toaster />
                </main>
              </Suspense>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
