import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Suspense } from "react";
import { BeatLoader } from "react-spinners";

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${geistSans.variable} antialiased`}
      >
        <div className="font-[family-name:var(--font-geist-sans)] flex relative min-h-screen">
          <div className="relative z-10 flex w-full h-screen">
            <Sidebar />
            <Suspense fallback={
              <div className="w-full h-full flex justify-center items-center z-50">
                <BeatLoader color='#ffffff' size={10} />
              </div>
            }>
              <main className="flex flex-col flex-1 overflow-auto scrollbar-thin duration-300">
                {children}
              </main>
            </Suspense>
          </div>
        </div>
      </body>
    </html>
  );
}
